# Generated by Django 5.1.2 on 2025-01-26 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='cs_lv_code',
            field=models.ForeignKey(blank=True, help_text='Foreign key to Level', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.level', verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='cs_sf_num',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='ch_cs_code',
            field=models.ForeignKey(help_text='Foreign key to Class Subject', on_delete=django.db.models.deletion.CASCADE, to='sadmin.classsubject', verbose_name='Class Subject'),
        ),
    ]
