# Generated by Django 5.1.2 on 2024-11-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('cu_num', models.AutoField(help_text='Code uniquely identify a Currecny', primary_key=True, serialize=False, verbose_name='Currecny ID')),
                ('cu_code', models.CharField(help_text='The currency Code', max_length=3, verbose_name='Code')),
                ('cu_name', models.CharField(help_text='Currency Name', max_length=100, verbose_name='Currency Name')),
                ('cu_base', models.CharField(choices=[('Y', 'Home Currency'), ('1', 'Currency 1'), ('2', 'Currency 1')], default='N', help_text='Indicates whether the currency is the base currency', max_length=1, verbose_name='Base Currency ?')),
                ('cu_rate', models.DecimalField(decimal_places=2, default=0, help_text='Rate to base', max_digits=15, verbose_name='Rate to base')),
                ('cu_valid_from', models.DateTimeField(help_text='Date date from which rate is valid', verbose_name='Valid From')),
                ('cu_status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', help_text='Status of the currency', max_length=1, verbose_name='Status')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'ordering': ['cu_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='classmember',
            options={'ordering': ['cm_surname'], 'verbose_name': 'Class Member'},
        ),
        migrations.AlterModelOptions(
            name='facilityspace',
            options={'ordering': ['fs_num'], 'verbose_name': 'Facility Space'},
        ),
        migrations.AlterModelOptions(
            name='levelclass',
            options={'ordering': ['lc_num'], 'verbose_name': 'Level Class'},
        ),
        migrations.AlterModelOptions(
            name='levelclassinstance',
            options={'ordering': ['ci_num'], 'verbose_name': 'Level Class Instance'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['sc_code'], 'verbose_name': 'School Class'},
        ),
        migrations.AlterModelOptions(
            name='spaceslot',
            options={'ordering': ['sp_num'], 'verbose_name': 'Space Slot'},
        ),
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['sf_surname'], 'verbose_name': 'Staff Member'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sb_lv_code',
        ),
        migrations.AddField(
            model_name='level',
            name='lv_sb_code',
            field=models.ForeignKey(default=1, help_text='The subject for the study level', on_delete=django.db.models.deletion.CASCADE, to='sadmin.subject', verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='levelclass',
            name='lc_sf_num',
            field=models.ForeignKey(default=1, help_text='Staff member assigned', on_delete=django.db.models.deletion.CASCADE, to='sadmin.staffmember', verbose_name='Staff Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='sc_sf_num',
            field=models.ForeignKey(default=1, help_text='Staff member assigned', on_delete=django.db.models.deletion.CASCADE, to='sadmin.staffmember', verbose_name='Staff Member'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassAssessment',
            fields=[
                ('as_num', models.AutoField(help_text='System generated number uniquely identifying an Assessment', primary_key=True, serialize=False, verbose_name='Number')),
                ('as_type', models.CharField(choices=[('1', 'Homework'), ('2', 'Tests'), ('3', 'End Of Session Exam')], help_text='Type of the assessment', max_length=1, verbose_name='Type')),
                ('as_name', models.CharField(help_text='Name of the assessment', max_length=100, verbose_name='Name')),
                ('as_remark', models.CharField(help_text='Any remarks', max_length=100, verbose_name='Remark')),
                ('as_exception', models.CharField(help_text='Exceptions noted', max_length=100, verbose_name='Exceptions')),
                ('as_comment', models.CharField(help_text='Any comments', max_length=100, verbose_name='Comment')),
                ('as_review', models.CharField(help_text='Review of the assessment', max_length=100, verbose_name='Review')),
                ('as_resources', models.CharField(help_text='Resource requirements', max_length=100, verbose_name='Resources')),
                ('as_trans_date', models.DateTimeField(help_text='Date to be taken', verbose_name='Trans Date')),
                ('as_status', models.CharField(choices=[('1', 'On'), ('2', 'Off')], default='1', help_text='Status', max_length=1, verbose_name='Status')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
                ('as_lc_num', models.ForeignKey(help_text='The Level Class', on_delete=django.db.models.deletion.CASCADE, related_name='level_key', to='sadmin.levelclass', verbose_name='Level Class')),
                ('as_lv_code', models.ForeignKey(help_text='Foreign key to Level', on_delete=django.db.models.deletion.CASCADE, related_name='lv_key', to='sadmin.level', verbose_name='Level')),
                ('as_sb_code', models.ForeignKey(help_text='Foreign key to Subject', on_delete=django.db.models.deletion.CASCADE, related_name='sb_key', to='sadmin.subject', verbose_name='Subject')),
                ('as_sc_code', models.ForeignKey(help_text='Foreign key to School Class', on_delete=django.db.models.deletion.CASCADE, related_name='sc_key', to='sadmin.schoolclass', verbose_name='School Class')),
            ],
            options={
                'verbose_name': 'Class Assessment',
                'ordering': ['as_num'],
            },
        ),
        migrations.CreateModel(
            name='LearnerAssessment',
            fields=[
                ('la_num', models.AutoField(help_text='Unique identifier for a Learner Assessment', primary_key=True, serialize=False, verbose_name='Number')),
                ('la_type', models.CharField(choices=[('1', 'Academic'), ('2', 'Sport'), ('3', 'Extra Carricular')], help_text='Type of the Subject', max_length=1, verbose_name='Type')),
                ('la_remark', models.CharField(help_text='The remark on the Learner Assessment', max_length=100, verbose_name='Remark')),
                ('la_comment', models.CharField(help_text='Comment on the Learner Assessment', max_length=100, verbose_name='Comment')),
                ('la_mark_f', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Forecasted mark', max_digits=5, null=True, verbose_name='Forcast Mark')),
                ('la_grade_f', models.CharField(help_text='Forcast grade', max_length=5, verbose_name='Forcast Grade')),
                ('la_mark_a', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Actual mark', max_digits=5, null=True, verbose_name='Actual Mark')),
                ('la_grade_a', models.CharField(help_text='Actual grade', max_length=5, verbose_name='Actual Grade')),
                ('la_status', models.CharField(choices=[('1', 'On'), ('2', 'Off')], default='1', help_text='Status', max_length=1, verbose_name='Status')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
                ('la_cm_num', models.ForeignKey(help_text='The Level Class', on_delete=django.db.models.deletion.CASCADE, to='sadmin.levelclass', verbose_name='Class ember')),
                ('la_lc_num', models.ForeignKey(help_text='The Level Class', on_delete=django.db.models.deletion.CASCADE, related_name='la_lc_key', to='sadmin.levelclass', verbose_name='Level Class')),
                ('la_lv_code', models.ForeignKey(help_text='Foreign key to Level', on_delete=django.db.models.deletion.CASCADE, related_name='la_lv_key', to='sadmin.level', verbose_name='Level')),
                ('la_sb_code', models.ForeignKey(help_text='Foreign key to Subject', on_delete=django.db.models.deletion.CASCADE, related_name='la_sb_key', to='sadmin.subject', verbose_name='Subject')),
                ('la_sc_code', models.ForeignKey(help_text='Foreign key to School Class', on_delete=django.db.models.deletion.CASCADE, related_name='la_sc_key', to='sadmin.schoolclass', verbose_name='School Class')),
            ],
            options={
                'verbose_name': 'Learner Assessment',
                'ordering': ['la_num'],
            },
        ),
    ]
