# Generated by Django 5.1.2 on 2025-01-26 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_classsubject_cs_lv_code_classsubject_cs_sf_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='sp_cs_code',
            field=models.ForeignKey(default=1, help_text='Foreign key to Class Subject', on_delete=django.db.models.deletion.CASCADE, to='sadmin.classsubject', verbose_name='Class Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='sp_lc_num',
            field=models.ForeignKey(blank=True, help_text='Level Class', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.levelclass', verbose_name='Level Class'),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='ch_lc_num',
            field=models.ForeignKey(blank=True, help_text='Level Class', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.levelclass', verbose_name='Level Class'),
        ),
    ]
