# Generated by Django 5.1.2 on 2024-11-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_alter_classmember_cm_dob_alter_classmember_cm_doj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceslot',
            name='sp_fs_num',
            field=models.ForeignKey(help_text='Foreign key to SchoolClass', on_delete=django.db.models.deletion.CASCADE, to='sadmin.facilityspace', verbose_name='School Class'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_status',
            field=models.CharField(choices=[('1', 'Applicant'), ('2', 'Engaged'), ('3', 'Discharged'), ('4', 'Pending'), ('5', 'On Leave')], default='1', help_text='Status', max_length=1, verbose_name='Status'),
        ),
    ]
