# Generated by Django 5.1.2 on 2025-01-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_alter_schemes_ch_lv_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='ch_ex_board',
            field=models.CharField(blank=True, choices=[('1', 'Zim Sec'), ('2', 'Cambridge')], default='1', help_text='Examination Board', max_length=1, null=True, verbose_name='Exam Board'),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='ch_sy_code',
            field=models.ForeignKey(blank=True, help_text='The syllabus for subject of the study level', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.syllabus', verbose_name='Syllabus'),
        ),
    ]
