# Generated by Django 5.1.2 on 2024-11-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_alter_spaceslot_sp_fs_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classassessment',
            name='as_lv_code',
        ),
        migrations.AddField(
            model_name='classassessment',
            name='as_ch_num',
            field=models.ForeignKey(blank=True, help_text='Foreign key to Schemes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ch_key', to='sadmin.schemes', verbose_name='Scheme'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='sc_sf_num',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AlterField(
            model_name='spaceslot',
            name='sp_fs_num',
            field=models.ForeignKey(help_text='Foreign key to Facility', on_delete=django.db.models.deletion.CASCADE, to='sadmin.facilityspace', verbose_name='Facility'),
        ),
    ]
