# Generated by Django 5.1.2 on 2024-11-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0005_remove_classassessment_as_lv_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerassessment',
            name='la_lv_code',
        ),
        migrations.RemoveField(
            model_name='learnerassessment',
            name='la_sb_code',
        ),
        migrations.AddField(
            model_name='learnerassessment',
            name='la_as_num',
            field=models.ForeignKey(default=1, help_text='Student s assessment', on_delete=django.db.models.deletion.CASCADE, related_name='la_as_num', to='sadmin.classassessment', verbose_name='Assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learnerassessment',
            name='la_cm_num',
            field=models.ForeignKey(help_text='The Student', on_delete=django.db.models.deletion.CASCADE, related_name='la_cm_key', to='sadmin.classmember', verbose_name='Student'),
        ),
    ]
