# Generated by Django 5.1.2 on 2024-11-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0006_remove_learnerassessment_la_lv_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmember',
            name='cm_surname',
            field=models.CharField(help_text='Class Member Surname', max_length=100, verbose_name='Surname'),
        ),
        migrations.CreateModel(
            name='MemberRegister',
            fields=[
                ('mr_num', models.AutoField(help_text='System generated number uniquely identifying a register record', primary_key=True, serialize=False, verbose_name='Number')),
                ('mr_comment', models.CharField(help_text='Class Member s Other Name', max_length=100, verbose_name='Other Name')),
                ('mr_date', models.DateTimeField(help_text='The date of attendance', verbose_name='Date')),
                ('mr_day', models.IntegerField(help_text='The day number', verbose_name='Day Number')),
                ('mr_mark', models.CharField(choices=[('1', 'Present'), ('2', 'Excused'), ('3', 'Absent')], default='1', help_text='Marked Indicator', max_length=1, verbose_name='Marked')),
                ('mr_status', models.CharField(choices=[('1', 'On'), ('2', 'Suspended'), ('3', 'Expelled')], default='1', help_text='Status', max_length=1, verbose_name='Status')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
                ('mr_cm_num', models.ForeignKey(help_text='The Student', on_delete=django.db.models.deletion.CASCADE, to='sadmin.classmember', verbose_name='Student')),
                ('mr_sc_code', models.ForeignKey(help_text='Foreign key to SchoolClass', on_delete=django.db.models.deletion.CASCADE, to='sadmin.schoolclass', verbose_name='School Class')),
            ],
            options={
                'verbose_name': 'Member Register',
                'ordering': ['mr_cm_num'],
            },
        ),
    ]
