# Generated by Django 5.1.2 on 2025-01-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0006_alter_classmember_cm_lv_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbilling',
            name='cb_sl_code',
            field=models.ForeignKey(default=1, help_text='The school level', on_delete=django.db.models.deletion.CASCADE, to='sadmin.schoollevel', verbose_name='School Level'),
            preserve_default=False,
        ),
    ]
