# Generated by Django 5.1.2 on 2025-01-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0007_classbilling_cb_sl_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectbilling',
            name='jb_sl_code',
            field=models.ForeignKey(default=1, help_text='The school level', on_delete=django.db.models.deletion.CASCADE, to='sadmin.schoollevel', verbose_name='School Level'),
            preserve_default=False,
        ),
    ]
