# Generated by Django 5.1.2 on 2024-11-30 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0009_dailyplan_sp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerassessment',
            name='la_sb_code',
            field=models.ForeignKey(default=1, help_text='Foreign key to Subject', on_delete=django.db.models.deletion.CASCADE, related_name='la_sb_key', to='sadmin.subject', verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberregister',
            name='mr_mark',
            field=models.CharField(choices=[('P', 'Present'), ('E', 'Excused'), ('A', 'Absent')], default='1', help_text='Marked Indicator', max_length=1, verbose_name='Marked'),
        ),
    ]
