# Generated by Django 5.1.2 on 2025-01-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0009_alter_classassessment_as_lc_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceslot',
            name='sp_fromtime',
        ),
        migrations.RemoveField(
            model_name='spaceslot',
            name='sp_totime',
        ),
        migrations.AddField(
            model_name='spaceslot',
            name='sp_date',
            field=models.DateTimeField(blank=True, help_text='Required hrs for Subject', null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='spaceslot',
            name='sp_day',
            field=models.IntegerField(blank=True, help_text='Day of the session', null=True, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='spaceslot',
            name='sp_fc_num',
            field=models.ForeignKey(default=1, help_text='Foreign key to Facility', on_delete=django.db.models.deletion.CASCADE, to='sadmin.facility', verbose_name='Facility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceslot',
            name='sp_finish_time',
            field=models.TimeField(blank=True, help_text='Finishing Time', null=True, verbose_name='Finish Time'),
        ),
        migrations.AddField(
            model_name='spaceslot',
            name='sp_sc_code',
            field=models.ForeignKey(blank=True, help_text='The school School Class', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.schoolclass', verbose_name='School Class'),
        ),
        migrations.AddField(
            model_name='spaceslot',
            name='sp_sf_num',
            field=models.ForeignKey(default=1, help_text='Staff member assigned', on_delete=django.db.models.deletion.CASCADE, to='sadmin.staffmember', verbose_name='Staff Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceslot',
            name='sp_start_time',
            field=models.TimeField(blank=True, help_text='Starting Time', null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='spaceslot',
            name='sp_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Duration', max_digits=10, null=True, verbose_name='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='staffsubject',
            name='ss_lv_code',
            field=models.ForeignKey(blank=True, help_text='Teaches up to level ?', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.level', verbose_name='Up to Level'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='sb_ex_board',
            field=models.CharField(blank=True, choices=[('1', 'Zim Sec'), ('2', 'Cambridge')], default='1', help_text='Examination Board', max_length=1, null=True, verbose_name='Exam Board'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='sy_lv_code',
            field=models.ForeignKey(blank=True, help_text='The Study Level', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.level', verbose_name='Level'),
        ),
    ]
