# Generated by Django 5.1.2 on 2025-01-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0010_remove_spaceslot_sp_fromtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceslot',
            name='sp_sf_num',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.staffmember', verbose_name='Staff Member'),
        ),
    ]
