# Generated by Django 5.1.2 on 2025-01-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0011_alter_spaceslot_sp_sf_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='termparameter',
            name='tp_end_time',
            field=models.TimeField(blank=True, help_text='Business finishing time', null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='termparameter',
            name='tp_start_time',
            field=models.TimeField(blank=True, help_text='Business start time', null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='spaceslot',
            name='sp_status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Taken')], default='1', help_text='Status', max_length=1, verbose_name='Status'),
        ),
    ]
