# Generated by Django 5.1.2 on 2025-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0012_termparameter_tp_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termparameter',
            name='tp_end_time',
            field=models.DateTimeField(blank=True, help_text='Business finishing time', null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='termparameter',
            name='tp_start_time',
            field=models.DateTimeField(blank=True, help_text='Business start time', null=True, verbose_name='Start Time'),
        ),
    ]
