# Generated by Django 5.1.2 on 2025-01-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0013_alter_termparameter_tp_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceslot',
            name='sp_fs_num',
            field=models.ForeignKey(help_text='Foreign key to Facility', on_delete=django.db.models.deletion.CASCADE, to='sadmin.facilityspace', verbose_name='Space'),
        ),
        migrations.AlterField(
            model_name='spaceslot',
            name='sp_type',
            field=models.CharField(choices=[('1', 'Academic'), ('2', 'Sport'), ('3', 'Extra Carricular')], default=1, help_text='Type of the slot', max_length=1, verbose_name='Type'),
        ),
    ]
