# Generated by Django 5.1.2 on 2024-12-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0013_schemes_ch_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermParameter',
            fields=[
                ('tp_num', models.AutoField(help_text='System generated number uniquely identifying a Level Class', primary_key=True, serialize=False, verbose_name='Number')),
                ('tp_year', models.CharField(help_text='Study Year', max_length=4, verbose_name='Year')),
                ('tp_term', models.IntegerField(help_text='The term of the year of study', max_length=1, verbose_name='Term')),
                ('tp_weeks', models.IntegerField(blank=True, default=0, help_text='Weeks in term', null=True, verbose_name='Weeks')),
                ('tp_days', models.IntegerField(blank=True, default=0, help_text='Days in term', null=True, verbose_name='Days')),
                ('tp_start_date', models.DateTimeField(help_text='Opening Day', verbose_name='Start Date')),
                ('tp_end_date', models.DateTimeField(help_text='Closng Day', verbose_name='End Date')),
                ('tp_status', models.CharField(choices=[('1', 'On'), ('2', 'Off')], default='1', help_text='Status', max_length=1, verbose_name='Status')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Term',
                'ordering': ['tp_year', 'tp_term'],
            },
        ),
    ]
