# Generated by Django 5.1.2 on 2025-01-31 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0014_alter_spaceslot_sp_fs_num_alter_spaceslot_sp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_1',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 1'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_10',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 10'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_2',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 2'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_3',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 3'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_4',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 4'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_5',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 5'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_6',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 6'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_7',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 7'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_8',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 8'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_mark_9',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent'), ('H', 'Holiday')], default='A', help_text='Marked Indicator', max_length=1, verbose_name='Subject 9'),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_sp_num',
            field=models.ForeignKey(default=1, help_text='Daily Plan', on_delete=django.db.models.deletion.CASCADE, to='sadmin.dailyplan', verbose_name='Daily Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='sb_num',
            field=models.IntegerField(blank=True, help_text='Number for linking with register', null=True, verbose_name='Subject Number'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='cs_name',
            field=models.CharField(help_text='Subject Name', max_length=100, verbose_name='Subject Name'),
        ),
    ]
