# Generated by Django 5.1.2 on 2024-12-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0014_termparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termparameter',
            name='tp_term',
            field=models.IntegerField(help_text='The term of the year of study', verbose_name='Term'),
        ),
    ]
