# Generated by Django 5.1.2 on 2024-12-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0015_alter_termparameter_tp_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelclass',
            name='lc_scheme_status',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', help_text='Indicates whether a scheme has been generated', max_length=1, verbose_name='Scheme Status'),
        ),
    ]
