# Generated by Django 5.1.2 on 2025-02-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0015_memberregister_mr_mark_1_memberregister_mr_mark_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregister',
            name='mr_sp_num',
            field=models.ForeignKey(blank=True, help_text='Daily Plan', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.dailyplan', verbose_name='Daily Plan'),
        ),
    ]
