# Generated by Django 5.1.2 on 2024-12-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0016_levelclass_lc_scheme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='termparameter',
            name='tp_schemed',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Scheduled'), ('2', 'Processed')], default='0', help_text='Schemed', max_length=1, verbose_name='Schemed?'),
        ),
    ]
