# Generated by Django 5.1.2 on 2025-02-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0016_alter_memberregister_mr_sp_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='cs_status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='0', help_text='Status of the Level', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_dob',
            field=models.DateTimeField(blank=True, help_text='Date of birth', null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_doj',
            field=models.DateTimeField(blank=True, help_text='Date Joined', null=True, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_dol',
            field=models.DateTimeField(blank=True, help_text='Date of leaving', null=True, verbose_name='Date of Leaving'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_email',
            field=models.CharField(default='Tba', help_text='Contact Email', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_fname',
            field=models.CharField(default='Tba', help_text='Staff Member First Name', max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_nok',
            field=models.CharField(default='Tba', help_text='Staff Member s next of kin', max_length=100, verbose_name='Next Of Kin'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_othername',
            field=models.CharField(default='Tba', help_text='Staff Member s Other Name', max_length=100, verbose_name='Other Name'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_phone',
            field=models.CharField(default='Tba', help_text='Contact phone', max_length=100, verbose_name='Phone'),
        ),
    ]
