# Generated by Django 5.1.2 on 2025-02-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0017_alter_classsubject_cs_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='cs_status',
            field=models.CharField(choices=[('1', 'Available'), ('0', 'Unavailable')], default='0', help_text='Status of the Level', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='level',
            name='ad_date_c',
            field=models.DateTimeField(auto_now=True, help_text='Date record was created'),
        ),
        migrations.AlterField(
            model_name='level',
            name='lv_status',
            field=models.CharField(choices=[('1', 'Offered'), ('0', 'Unavailable')], default='1', help_text='Status of the Level', max_length=1, verbose_name='Status'),
        ),
    ]
