# Generated by Django 5.1.2 on 2024-12-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0017_termparameter_tp_schemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='termparameter',
            name='tp_period_len',
            field=models.IntegerField(blank=True, default=30, help_text='Length of period in minutes', null=True, verbose_name='Period Length'),
        ),
    ]
