# Generated by Django 5.1.2 on 2025-02-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0018_alter_classsubject_cs_status_alter_level_ad_date_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='lv_code',
            field=models.AutoField(help_text='The Level Code - Primary key for the table', primary_key=True, serialize=False, verbose_name='Code'),
        ),
    ]
