# Generated by Django 5.1.2 on 2024-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0018_termparameter_tp_period_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='sp_term',
            field=models.IntegerField(default=1, help_text='The term of the year of study', verbose_name='Term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='sp_year',
            field=models.CharField(default=1, help_text='Study Year', max_length=4, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemes',
            name='ch_term',
            field=models.IntegerField(default=1, help_text='The term of the year of study', verbose_name='Term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemes',
            name='ch_year',
            field=models.CharField(default=1, help_text='Study Year', max_length=4, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
