# Generated by Django 5.1.2 on 2025-02-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0019_alter_level_lv_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='ad_date_a',
            field=models.DateTimeField(auto_now=True, help_text='Date record was last amended', null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='ad_date_c',
            field=models.DateTimeField(auto_now=True, help_text='Date record was created', null=True),
        ),
    ]
