# Generated by Django 5.1.2 on 2024-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0019_dailyplan_sp_term_dailyplan_sp_year_schemes_ch_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='sp_absorption',
            field=models.CharField(blank=True, help_text='The methods to be used', max_length=100, null=True, verbose_name='Methods'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='sp_objective',
            field=models.CharField(blank=True, help_text='The objectives for the period', max_length=100, null=True, verbose_name='Objetives'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='sp_paction',
            field=models.IntegerField(blank=True, choices=[(80, 'more than 80 %'), (75, '75 %'), (50, '50 %'), (25, 'Less than 25 %')], help_text='Follow on action post delivery', null=True, verbose_name='Post Action'),
        ),
    ]
