# Generated by Django 5.1.2 on 2025-02-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0020_alter_level_ad_date_a_alter_level_ad_date_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='sf_ll_code',
            field=models.CharField(choices=[('1', 'Senoir Qualified'), ('2', 'Qualified'), ('3', 'Intern'), ('4', 'General')], default='1', help_text='Staff Lvel', max_length=1, verbose_name='Status'),
        ),
    ]
