# Generated by Django 5.1.2 on 2024-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0020_alter_dailyplan_sp_absorption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregister',
            name='mr_term',
            field=models.IntegerField(default=1, help_text='The term of the year of study', verbose_name='Term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberregister',
            name='mr_year',
            field=models.CharField(default=1, help_text='Study Year', max_length=4, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='sp_status',
            field=models.CharField(choices=[('0', 'Planned'), ('1', 'Delivered'), ('2', 'Deferred')], default='0', help_text='Status', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='memberregister',
            name='mr_mark',
            field=models.CharField(choices=[('P', 'Present'), ('E', 'Excused'), ('A', 'Absent')], default='P', help_text='Marked Indicator', max_length=1, verbose_name='Marked'),
        ),
    ]
