# Generated by Django 5.1.2 on 2025-02-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0021_staffmember_sf_ll_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='sf_ll_code',
            field=models.CharField(choices=[('1', 'Senoir Qualified'), ('2', 'Qualified'), ('3', 'Intern'), ('4', 'General')], default='1', help_text='Staff Lvel', max_length=1, verbose_name='Level'),
        ),
        migrations.CreateModel(
            name='authrelation',
            fields=[
                ('ar_num', models.AutoField(help_text='Code uniquely identify a table', primary_key=True, serialize=False, verbose_name='Code')),
                ('ar_sname', models.CharField(help_text='Surname', max_length=100, verbose_name='Surname')),
                ('ar_fname', models.CharField(help_text='First Name', max_length=100, verbose_name='First Name')),
                ('ar_nid', models.CharField(help_text='National ID', max_length=20, verbose_name='National ID')),
                ('ar_phone', models.CharField(help_text='Contact Phone', max_length=20, verbose_name='Phone')),
                ('ar_email', models.CharField(help_text='Email Address', max_length=100, verbose_name='Email')),
                ('ar_status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='0', help_text='Status of the Level', max_length=1, verbose_name='Status')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
                ('ar_cm_num', models.ForeignKey(help_text='Class Member (Student)', on_delete=django.db.models.deletion.CASCADE, to='sadmin.classmember', verbose_name='Class Member')),
                ('cm_sc_code', models.ForeignKey(help_text='Foreign key to SchoolClass', on_delete=django.db.models.deletion.CASCADE, to='sadmin.schoolclass', verbose_name='School Class')),
            ],
            options={
                'verbose_name': 'Relations',
                'ordering': ['ar_sname'],
            },
        ),
        migrations.CreateModel(
            name='membermovement',
            fields=[
                ('mm_num', models.AutoField(help_text='Code uniquely identify a table', primary_key=True, serialize=False, verbose_name='Code')),
                ('mm_day', models.IntegerField(help_text='Day of the term', verbose_name='Day')),
                ('mm_date_dr', models.DateTimeField(help_text='Date and time for placement', verbose_name='Date Time')),
                ('mm_dr_status', models.CharField(choices=[('0', 'Expected'), ('1', 'Set'), ('2', 'Placed')], default='0', help_text='Status', max_length=1, verbose_name='Status')),
                ('mm_dr_notes', models.CharField(help_text='Placement Notes', max_length=20, verbose_name='Notes')),
                ('mm_date_pk', models.DateTimeField(help_text='Date and time for pickup', verbose_name='Date Time')),
                ('mm_pk_status', models.CharField(choices=[('0', 'Waiting'), ('1', 'Set'), ('2', 'Picked')], default='0', help_text='Status', max_length=1, verbose_name='Status')),
                ('mm_pk_notes', models.CharField(help_text='pickup Notes', max_length=20, verbose_name='Notes')),
                ('mm_status', models.CharField(choices=[('0', 'Open'), ('1', 'Set'), ('2', 'Closed')], default='0', help_text='Status of the movement', max_length=1, verbose_name='Status')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
                ('mm_cm_num', models.ForeignKey(help_text='Class Member (Student)', on_delete=django.db.models.deletion.CASCADE, to='sadmin.classmember', verbose_name='Class Member')),
                ('mm_dr_ar_num', models.ForeignKey(help_text='Authorized Relation', on_delete=django.db.models.deletion.CASCADE, related_name='dr_num_key', to='sadmin.classmember', verbose_name='Relation')),
                ('mm_fs_num', models.ForeignKey(help_text='Current location', on_delete=django.db.models.deletion.CASCADE, to='sadmin.facilityspace', verbose_name='Location')),
                ('mm_pk_ar_num', models.ForeignKey(help_text='Authorized Relation', on_delete=django.db.models.deletion.CASCADE, related_name='pk_num_key', to='sadmin.classmember', verbose_name='Relation')),
                ('mm_sc_code', models.ForeignKey(help_text='Foreign key to SchoolClass', on_delete=django.db.models.deletion.CASCADE, to='sadmin.schoolclass', verbose_name='School Class')),
            ],
            options={
                'verbose_name': 'membermovement',
                'ordering': ['mm_day'],
            },
        ),
    ]
