# Generated by Django 5.1.2 on 2024-12-28 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0021_memberregister_mr_term_memberregister_mr_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregister',
            name='mr_mark',
            field=models.CharField(choices=[('P', 'Present'), ('S', 'Sick'), ('A', 'Absent')], default='P', help_text='Marked Indicator', max_length=1, verbose_name='Marked'),
        ),
        migrations.CreateModel(
            name='ClassBilling',
            fields=[
                ('cb_num', models.AutoField(help_text='System generated number uniquely identifying a Level Class', primary_key=True, serialize=False, verbose_name='Number')),
                ('cb_type', models.CharField(choices=[('1', 'Academic'), ('2', 'Sport'), ('3', 'Extra Carricular')], help_text='Type of the Subject', max_length=1, verbose_name='Type')),
                ('cb_desc', models.CharField(help_text='The description of the Rate', max_length=100, verbose_name='Name')),
                ('cb_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Rate', max_digits=10, null=True, verbose_name='Rate')),
                ('cb_year', models.CharField(help_text='Study Year', max_length=4, verbose_name='Year')),
                ('cb_term', models.IntegerField(help_text='The term of the year of study', verbose_name='Term')),
                ('cb_status', models.CharField(choices=[('1', 'On'), ('2', 'Off')], default='1', help_text='Status', max_length=1, verbose_name='Status')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
                ('cb_lv_code', models.ForeignKey(help_text='Foreign key to Level', on_delete=django.db.models.deletion.CASCADE, related_name='cb_lv', to='sadmin.level', verbose_name='Level')),
                ('cb_sc_code', models.ForeignKey(help_text='Foreign key to SchoolClass', on_delete=django.db.models.deletion.CASCADE, related_name='cb_sc', to='sadmin.schoolclass', verbose_name='School Class')),
            ],
            options={
                'verbose_name': 'ClassBilling',
                'ordering': ['cb_num'],
            },
        ),
        migrations.CreateModel(
            name='SubjectBilling',
            fields=[
                ('jb_num', models.AutoField(help_text='System generated number uniquely identifying a Level Class', primary_key=True, serialize=False, verbose_name='Number')),
                ('jb_type', models.CharField(choices=[('1', 'Academic'), ('2', 'Sport'), ('3', 'Extra Carricular')], help_text='Type of the Subject', max_length=1, verbose_name='Type')),
                ('jb_desc', models.CharField(help_text='The description of the Subject', max_length=100, verbose_name='Name')),
                ('jb_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Rate', max_digits=10, null=True, verbose_name='Req. Hrs')),
                ('jb_status', models.CharField(choices=[('1', 'On'), ('2', 'Off')], default='1', help_text='Status', max_length=1, verbose_name='Status')),
                ('jb_year', models.CharField(help_text='Study Year', max_length=4, verbose_name='Year')),
                ('jb_term', models.IntegerField(help_text='The term of the year of study', verbose_name='Term')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
                ('jb_lc_num', models.ForeignKey(help_text='Foreign key to Level Class', on_delete=django.db.models.deletion.CASCADE, related_name='jb_lc', to='sadmin.schoolclass', verbose_name='Level Class')),
                ('jb_lv_code', models.ForeignKey(help_text='Foreign key to Level', on_delete=django.db.models.deletion.CASCADE, related_name='jb_lv', to='sadmin.level', verbose_name='Level')),
                ('jb_sb_code', models.ForeignKey(help_text='Foreign key to Subject', on_delete=django.db.models.deletion.CASCADE, related_name='jb_sb', to='sadmin.subject', verbose_name='Subject')),
                ('jb_sc_code', models.ForeignKey(help_text='Foreign key to SchoolClass', on_delete=django.db.models.deletion.CASCADE, related_name='jb_sc', to='sadmin.schoolclass', verbose_name='School Class')),
            ],
            options={
                'verbose_name': 'SubjectBilling',
                'ordering': ['jb_num'],
            },
        ),
    ]
