# Generated by Django 5.1.2 on 2025-02-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0022_alter_staffmember_sf_ll_code_authrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermovement',
            name='mm_date',
            field=models.DateTimeField(blank=True, help_text='Date of placement', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_date_dr',
            field=models.DateTimeField(help_text='Time of placement', verbose_name='Placement Time'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_date_pk',
            field=models.DateTimeField(help_text='Time of pickup', verbose_name='Pickup Time'),
        ),
    ]
