# Generated by Django 5.1.2 on 2024-12-29 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0022_alter_memberregister_mr_mark_classbilling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbilling',
            name='cb_type',
            field=models.CharField(choices=[('1', 'Academic'), ('2', 'Sport'), ('3', 'Extra Carricular'), ('4', 'Practical')], default='1', help_text='Type of the Subject', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='subjectbilling',
            name='jb_desc',
            field=models.CharField(help_text='The description of the billing head', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subjectbilling',
            name='jb_lc_num',
            field=models.ForeignKey(help_text='Foreign key to Level Class', on_delete=django.db.models.deletion.CASCADE, related_name='jb_lc', to='sadmin.levelclass', verbose_name='Level Class'),
        ),
        migrations.AlterField(
            model_name='subjectbilling',
            name='jb_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Rate', max_digits=10, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='subjectbilling',
            name='jb_type',
            field=models.CharField(choices=[('1', 'Academic'), ('2', 'Sport'), ('3', 'Extra Carricular'), ('4', 'Practical')], default='1', help_text='Type of the Subject', max_length=1, verbose_name='Type'),
        ),
    ]
