# Generated by Django 5.1.2 on 2025-02-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0024_rename_cm_sc_code_authrelation_ar_sc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrelation',
            name='ar_cm_num',
            field=models.ForeignKey(blank=True, help_text='Class Member (Student)', on_delete=django.db.models.deletion.CASCADE, to='sadmin.classmember', verbose_name='Class Member'),
        ),
        migrations.AlterField(
            model_name='authrelation',
            name='ar_sc_code',
            field=models.ForeignKey(blank=True, help_text='Foreign key to SchoolClass', on_delete=django.db.models.deletion.CASCADE, to='sadmin.schoolclass', verbose_name='School Class'),
        ),
    ]
