# Generated by Django 5.1.2 on 2025-02-20 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0025_alter_authrelation_ar_cm_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermovement',
            name='mm_day',
            field=models.IntegerField(blank=True, help_text='Day of the term', null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_dr_ar_num',
            field=models.ForeignKey(help_text='Authorized Relation', on_delete=django.db.models.deletion.CASCADE, related_name='dr_num_key', to='sadmin.authrelation', verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_dr_status',
            field=models.CharField(choices=[('0', 'Expected'), ('1', 'Set'), ('2', 'Placed')], default='0', help_text='Status', max_length=1, verbose_name='Placed - Status'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_fs_num',
            field=models.ForeignKey(blank=True, help_text='Current location', null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.facilityspace', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_pk_ar_num',
            field=models.ForeignKey(help_text='Authorized Relation', on_delete=django.db.models.deletion.CASCADE, related_name='pk_num_key', to='sadmin.authrelation', verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_pk_status',
            field=models.CharField(choices=[('0', 'Waiting'), ('1', 'Set'), ('2', 'Picked')], default='0', help_text='Status', max_length=1, verbose_name='Picked - Status'),
        ),
    ]
