# Generated by Django 5.1.2 on 2024-12-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0026_memberrecord_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='rc_term',
            field=models.IntegerField(default=1, help_text='Term for which the fees are considered', verbose_name='Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='rc_year',
            field=models.IntegerField(default=1, help_text='Year for which the fees are considered', verbose_name='Period'),
            preserve_default=False,
        ),
    ]
