# Generated by Django 5.1.2 on 2025-02-20 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0026_alter_membermovement_mm_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermovement',
            name='mm_date_dr',
            field=models.DateTimeField(blank=True, help_text='Time of placement', null=True, verbose_name='Placement Time'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_date_pk',
            field=models.DateTimeField(blank=True, help_text='Time of pickup', null=True, verbose_name='Pickup Time'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_dr_ar_num',
            field=models.ForeignKey(blank=True, help_text='Authorized Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dr_num_key', to='sadmin.authrelation', verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_dr_notes',
            field=models.CharField(blank=True, help_text='Placement Notes', max_length=20, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_dr_status',
            field=models.CharField(blank=True, choices=[('0', 'Expected'), ('1', 'Set'), ('2', 'Placed')], default='0', help_text='Status', max_length=1, null=True, verbose_name='Placed - Status'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_pk_ar_num',
            field=models.ForeignKey(blank=True, help_text='Authorized Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_num_key', to='sadmin.authrelation', verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_pk_notes',
            field=models.CharField(blank=True, help_text='pickup Notes', max_length=20, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_pk_status',
            field=models.CharField(blank=True, choices=[('0', 'Waiting'), ('1', 'Set'), ('2', 'Picked')], default='0', help_text='Status', max_length=1, null=True, verbose_name='Picked - Status'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_status',
            field=models.CharField(blank=True, choices=[('0', 'Open'), ('1', 'Set'), ('2', 'Closed')], default='0', help_text='Status of the movement', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
