# Generated by Django 5.1.2 on 2024-12-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0027_receipt_rc_term_receipt_rc_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='mr_jb_num',
            field=models.ForeignKey(blank=True, help_text='Name of the subject based fee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mr_sb', to='sadmin.subjectbilling', verbose_name='Billing Head'),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='mr_cb_num',
            field=models.ForeignKey(blank=True, help_text='Name of the class based fee ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mr_lv', to='sadmin.classbilling', verbose_name='Billing Head'),
        ),
    ]
