# Generated by Django 5.1.2 on 2025-02-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0028_alter_membermovement_ad_date_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermovement',
            name='mm_date_dr',
            field=models.TimeField(blank=True, help_text='Time of placement', null=True, verbose_name='Placement Time'),
        ),
        migrations.AlterField(
            model_name='membermovement',
            name='mm_date_pk',
            field=models.TimeField(blank=True, help_text='Time of pickup', null=True, verbose_name='Pickup Time'),
        ),
    ]
