# Generated by Django 5.1.2 on 2025-01-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0028_memberrecord_mr_jb_num_alter_memberrecord_mr_cb_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classmember',
            old_name='cm_Email',
            new_name='cm_email',
        ),
        migrations.RenameField(
            model_name='classmember',
            old_name='cm_Guardian',
            new_name='cm_guardian',
        ),
        migrations.RenameField(
            model_name='classmember',
            old_name='cm_Phone',
            new_name='cm_phone',
        ),
    ]
