# Generated by Django 5.1.2 on 2025-01-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0029_rename_cm_email_classmember_cm_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='mr_term',
            field=models.IntegerField(help_text='Term for which the fees are considered', verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rc_period',
            field=models.IntegerField(blank=True, help_text='Period in which transaction occurred', null=True, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rc_year',
            field=models.IntegerField(help_text='Year for which the fees are considered', verbose_name='Year'),
        ),
    ]
