# Generated by Django 5.1.2 on 2025-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0030_dailyplan_sp_sl_code_schemes_ch_sl_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='sp_hnotes',
            field=models.CharField(blank=True, help_text='Homework Notes', max_length=100, null=True, verbose_name='Homework?'),
        ),
    ]
