# Generated by Django 5.1.2 on 2025-01-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0031_alter_receipt_rc_cm_num_alter_receipt_rc_lv_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='rc_processed',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Processed')], default='1', help_text='Processed ?', max_length=1, verbose_name='Processed'),
        ),
    ]
