# Generated by Django 5.1.2 on 2025-01-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0032_alter_receipt_rc_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmember',
            name='cm_gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', help_text='Gender', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='ch_status',
            field=models.CharField(choices=[('1', 'Done'), ('2', 'Pending'), ('3', 'Cancelled')], default='1', help_text='Status', max_length=1, verbose_name='Status'),
        ),
    ]
