# Generated by Django 5.1.2 on 2025-01-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0033_classmember_cm_gender_alter_schemes_ch_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='sf_Email',
            new_name='sf_email',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='sf_otherName',
            new_name='sf_othername',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='sf_Phone',
            new_name='sf_phone',
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='sf_app_status',
            field=models.CharField(choices=[('1', 'Academic'), ('2', 'Sport'), ('3', 'Extra Carricular')], default='1', help_text='Indicates Tyoe e.g. Academic', max_length=1, verbose_name='Staff Type'),
        ),
    ]
