# Generated by Django 5.1.2 on 2025-01-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0035_alter_schemes_ch_competencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='sp_status',
            field=models.CharField(choices=[('0', 'Planned'), ('1', 'Delivered'), ('2', 'Deferred'), ('W', 'Weekend')], default='0', help_text='Status', max_length=1, verbose_name='Status'),
        ),
    ]
