# Generated by Django 5.1.2 on 2025-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0037_dailyplan_sp_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='termparameter',
            name='tp_cycledays',
            field=models.IntegerField(blank=True, default=5, help_text='Days in Cycle', null=True, verbose_name=' Cycle Days'),
        ),
    ]
