# Generated by Django 5.1.2 on 2025-01-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0040_postcategory_postorigin_blogpost_postcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmember',
            name='cm_year',
            field=models.CharField(blank=True, help_text='Study Year', max_length=4, null=True, verbose_name='Year'),
        ),
    ]
