# Generated by Django 5.1.2 on 2025-01-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0041_classmember_cm_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='sb_hrs',
            field=models.IntegerField(default=1, help_text='Seats Available in Class', verbose_name='Seats'),
        ),
    ]
