# Generated by Django 5.1.2 on 2025-01-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0042_schoolclass_sb_hrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclass',
            old_name='sb_hrs',
            new_name='sc_hrs',
        ),
    ]
