# Generated by Django 5.1.2 on 2025-01-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0043_rename_sb_hrs_schoolclass_sc_hrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclass',
            old_name='sc_hrs',
            new_name='sc_seats',
        ),
    ]
