# Generated by Django 5.1.2 on 2025-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0044_rename_sc_hrs_schoolclass_sc_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='termparameter',
            name='tp_seats',
            field=models.IntegerField(default=1, help_text='General number of seats per class', verbose_name='General Seats'),
            preserve_default=False,
        ),
    ]
