# Generated by Django 5.1.2 on 2025-01-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0045_termparameter_tp_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classmember',
            old_name='cm_otherName',
            new_name='cm_othername',
        ),
    ]
