# Generated by Django 5.1.2 on 2025-01-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0046_rename_cm_othername_classmember_cm_othername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmember',
            name='cm_dob',
            field=models.DateTimeField(blank=True, help_text='Date of birth', null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='cm_doj',
            field=models.DateTimeField(blank=True, help_text='Date Joined', null=True, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='cm_dol',
            field=models.DateTimeField(blank=True, help_text='Date of leaving', null=True, verbose_name='Date of Leaving'),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='cm_email',
            field=models.CharField(blank=True, help_text='Contact Email', max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='cm_phone',
            field=models.CharField(blank=True, help_text='Contact phone', max_length=100, null=True, verbose_name='Phone'),
        ),
    ]
